# Generated by Django 5.1.4 on 2025-02-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='clienturl',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
