# Generated by Django 5.1.4 on 2025-02-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='clientview',
            field=models.CharField(default=1, max_length=190),
            preserve_default=False,
        ),
    ]
