# Generated by Django 5.1.4 on 2025-02-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userinfo_url_tracking_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='hitcount',
            field=models.IntegerField(default=1),
        ),
    ]
