# Generated by Django 5.1.4 on 2025-02-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userinfo_hitcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='hitcount',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='hit_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
